




language: objective-c



env:




  global:

    # The BINSTAR_TOKEN secure variable. This is defined canonically in forge.yml.
    - secure: "P4L9t6CRubcwWh4sVpCgGJRQ8yWa6zl/284q9p1m2LF29pqZa31nn/palni50ugKuhBBICWziYfdXWHdCTfUVVoJFkXhIRNJb7HjnfcgJfjzTs79lDGm45urUVT9LC9j3wEsA/zM4cbrZR+vasGkKtuc/Uk6PNApce1dIf/WYHo="





install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-3.7.3-MacOSX-x86_64.sh"
      wget "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda update --yes conda
      conda install --yes conda-build jinja2 binstar

script:
  - conda build .

after_success:
  - ./ci_support/upload_or_check_non_existence.py ./ conda-forge --channel=main